# YAML file for the crtk_lib_cpp rosparameters

robot_namespace: ""
arm_namespace: "arm1/"
grasper_namespace: "grasp1/"
max_joints: 7

home_pos:       [0.0242, 0.0141, -0.0780]
home_rot:       [0.12, 0.62, 0.07, 0.77] # in terms of quaternions
home_jpos:      [0.524, 1.583, 0.400, 0.0660, 0.0598, 0.736, 0.844]


# EXAMPLES:
# 
# ------------------------- Raven Left Arm -------------------------
# robot_namespace: ""
# arm_namespace: "arm0/"
# grasper_namespace: "grasp0/"
# max_joints: 7
# home_pos: [0.0239,-0.0144,-0.0779]
# home_rot: [-0.14,0.636,0.02,0.76]  
# home_jpos: [0.523, 1.584, 0.4002, 0.0715, 0.0950, 0.7537, 0.852]
# 
#  ------------------------ Raven Right Arm ------------------------
# robot_namespace: ""
# arm_namespace: "arm1/"
# grasper_namespace: "grasp1/"
# max_joints: 7
# home_pos: [0.0242, 0.0141,-0.0780]
# home_rot: [0.12,0.62,0.07,0.77]  
# home_jpos: [0.524, 1.583, 0.400, 0.0660, 0.0598, 0.736, 0.844]
